#! /usr/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0

~/.config/bspwm/borderbspwm &

bspc config window_gap          25

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Microsoft-edge desktop='^2' follow=on focus=on state=tiled
bspc rule -a sioyek desktop='^3' follow=on focus=on state=tiled


## Start programs and set last configs

bluetoothctl power off

#picom -b --shadow --animations --animation-window-mass 0.5 --animation-for-open-window zoom --animation-stiffness 350 &
picom --vsync --backend glx --glx-no-stencil --glx-no-rebind-pixmap &

xsetroot -cursor_name left_ptr
xset r rate 200 50

feh --no-fehbg --bg-fill /home/lilin/Pictures/wallpaper/*

polybar &
